### ISSUE TITLE
[BUG] Incorrect swap route from usdt on avalanche chain to polygon

### ISSUE THREAD

**Issue by aminsato** [vultisig/vultisig-android#1277]
The current route for swapping from USDT on the Avalanche chain to the Polygon chain is incorrect; there’s no direct swap route between these networks on 1Inch. The swap results in a WAWAX token instead

**Snowtrace Explorer**
https://snowtrace.io/tx/0xc8857c337b233557f2281c75cdfddbcf93bf8dc41ccac28be5d9ab7d3c8f2ce8

**Screen Record**

https://github.com/user-attachments/assets/598991fa-451e-43d2-97d6-336466c6a651

**Comment by Tao546127REP** [comment]
> The current route for swapping from USDT on the Avalanche chain to the Polygon chain is incorrect; there’s no direct swap route between these networks on 1Inch. The swap results in a WAWAX token instead
> 
> **Snowtrace Explorer** https://snowtrace.io/tx/0xc8857c337b233557f2281c75cdfddbcf93bf8dc41ccac28be5d9ab7d3c8f2ce8
> 
> **Screen Record**
> 
>  Swap_USDT.AVAX._Polygon.mp4



Hey @aminsato It sounds like you’re encountering issues with swapping USDT between the Avalanche and Polygon chains on 1Inch. Since there’s no direct route, you might consider using an intermediary token, like bridging your USDT to Ethereum first, and then swapping it to USDT on the Polygon chain. Alternatively, check if there are other bridges or decentralized exchanges that support the swap directly. Always ensure to verify token contracts to avoid unintended tokens like WAWAX.
