### ISSUE TITLE
Fix keygen device list UI

### ISSUE THREAD

**Issue by yvebe** [vultisig/vultisig-android#270]
<img width="573" alt="image" src="https://github.com/vultisig/vultisig-android/assets/14962060/894065f2-518a-4f04-89a5-99b6a1dee144">

**Comment by aminsato** [comment]
@yvebe 
I checked the device list and compared it with Midgard, and here are the issues I found:

- When we have more than two devices, the list numbers start from 0 instead of 1 (fixed in #305 ).

- In Figma, we have "You can only send transactions with these two devices present," but in Android, we have "You can only send transactions with these 2 devices present." I'm not sure if we need to update this one or not.

- When a user chooses 2 out of 3 devices and only two devices are present in the key generation phase, with the backup device missing, we show "2 of 2 vault." for title. Shouldn't it be "2 of 3 vault"?

Please let me know if I missed anything.

**Comment by realpaaao** [comment]
@aminsato please have it congruent with figma as this is also what iOS uses, to ensure redundancy.
on third point if user selected initial 2/3 but only paired 2 and proceeded, the display "2 of 2 vault" is correct as the vault only has two devices.

**Comment by aminsato** [comment]
Fixed in #334  and #305
